/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/arale.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.평면.geometry} material={materials.매테리얼} position={[-0.68, -0.01, -3.29]} scale={[4.32, 1, 6.19]} />
      <mesh geometry={nodes.arale.geometry} material={materials['palette.002']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/arale.glb')
